export const cropDatabase = [
    {
        id: 'winter-wheat',
        name: 'Winter wheat',
        season: 'Autumn planting',
        maturityDays: 280,
        yieldTonnesPerHa: 7.2,
        pricePerTonne: 185,
        variableCostPerHa: 720,
        waterNeed: 'Medium',
        nutrientDemand: 'Medium',
        riskLevel: 'Low',
        soilSuitability: ['Loamy silt', 'Clay loam', 'Sandy loam'],
        marketDemand: 'High',
        description: 'Strong winter resilience and dependable milling demand across mixed farm rotations.',
        profitability: 93,
    },
    {
        id: 'barley',
        name: 'Barley',
        season: 'Autumn planting',
        maturityDays: 240,
        yieldTonnesPerHa: 6.4,
        pricePerTonne: 162,
        variableCostPerHa: 650,
        waterNeed: 'Low',
        nutrientDemand: 'Medium',
        riskLevel: 'Low',
        soilSuitability: ['Clay loam', 'Loamy silt', 'Sandy loam'],
        marketDemand: 'High',
        description: 'Fast-turn crop with steady demand, lower irrigation need, and good rotation value.',
        profitability: 88,
    },
    {
        id: 'oilseed-rape',
        name: 'Oilseed rape',
        season: 'Late summer drilling',
        maturityDays: 300,
        yieldTonnesPerHa: 3.8,
        pricePerTonne: 340,
        variableCostPerHa: 860,
        waterNeed: 'Medium',
        nutrientDemand: 'High',
        riskLevel: 'Medium',
        soilSuitability: ['Sandy loam', 'Loamy silt'],
        marketDemand: 'High',
        description: 'High-value break crop with strong oil demand and good fit for well-drained soils.',
        profitability: 90,
    },
    {
        id: 'grass-ley',
        name: 'Grass ley',
        season: 'Spring establishment',
        maturityDays: 120,
        yieldTonnesPerHa: 9.5,
        pricePerTonne: 110,
        variableCostPerHa: 520,
        waterNeed: 'Medium',
        nutrientDemand: 'Medium',
        riskLevel: 'Low',
        soilSuitability: ['Peaty loam', 'Loamy silt', 'Clay loam'],
        marketDemand: 'Medium',
        description: 'Reliable pasture system that supports soil structure, grazing, and balanced forage output.',
        profitability: 81,
    },
    {
        id: 'maize',
        name: 'Forage maize',
        season: 'Spring planting',
        maturityDays: 170,
        yieldTonnesPerHa: 16,
        pricePerTonne: 96,
        variableCostPerHa: 980,
        waterNeed: 'High',
        nutrientDemand: 'High',
        riskLevel: 'Medium',
        soilSuitability: ['Loamy silt', 'Sandy loam'],
        marketDemand: 'Medium',
        description: 'High biomass crop for silage, best where water access and fertility are well managed.',
        profitability: 84,
    },
    {
        id: 'peas',
        name: 'Field peas',
        season: 'Spring planting',
        maturityDays: 160,
        yieldTonnesPerHa: 4.6,
        pricePerTonne: 220,
        variableCostPerHa: 610,
        waterNeed: 'Low',
        nutrientDemand: 'Medium',
        riskLevel: 'Medium',
        soilSuitability: ['Clay loam', 'Loamy silt'],
        marketDemand: 'Medium',
        description: 'Nitrogen-fixing pulse crop that boosts soil health and offers a solid protein market.',
        profitability: 78,
    },
];
